apiVersion: azure.crossplane.io/v1alpha3
kind: ResourceGroup
metadata:
  name: gitops-webinar-rg
spec:
  location: North Europe
---
apiVersion: database.azure.crossplane.io/v1beta1
kind: MySQLServer
metadata:
  name: gitops-webinar-2022
spec:
  forProvider:
    administratorLogin: myadmin
    resourceGroupNameRef:
      name:  gitops-webinar-rg
    location: North Europe
    minimalTlsVersion: TLS1_2
    sslEnforcement: Enabled
    version: "5.7"
    sku:
      tier: Basic
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretToRef:
    namespace: crossplane
    name: mysql-wordpress-creds
  providerConfigRef:
    name: default
---
apiVersion: database.azure.crossplane.io/v1alpha3
kind: MySQLServerFirewallRule
metadata:
  name: firewall-rule
spec:
  providerConfigRef:
    name: default
  forProvider:
    resourceGroupNameRef:
      name: gitops-webinar-rg
    serverNameRef:
      name: gitops-webinar-2022
    properties:
      startIpAddress: "0.0.0.0"
      endIpAddress: "0.0.0.0"
